package lockfile

import (
	"fmt"
	"os"
	"sort"
	"time"

	"gopkg.in/yaml.v3"
)

const Filename = "agentskills.lock"

// LockFile represents the agentskills.lock file.
type LockFile struct {
	Version   int                    `yaml:"version"`
	UpdatedAt string                 `yaml:"updated_at"`
	Skills    map[string]LockedSkill `yaml:"skills"`
}

// LockedSkill represents a single locked skill entry.
type LockedSkill struct {
	Version  string `yaml:"version"`
	Checksum string `yaml:"checksum"`
	Source   string `yaml:"source"`
}

// Load reads the lock file from the given path.
// Returns nil (no error) if the file does not exist.
func Load(path string) (*LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading lock file: %w", err)
	}

	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("parsing lock file: %w", err)
	}
	return &lf, nil
}

// Save writes the lock file to the given path.
func Save(path string, lf *LockFile) error {
	lf.Version = 1
	lf.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	// Sort skills for deterministic output
	sorted := make(map[string]LockedSkill, len(lf.Skills))
	keys := make([]string, 0, len(lf.Skills))
	for k := range lf.Skills {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		sorted[k] = lf.Skills[k]
	}
	lf.Skills = sorted

	data, err := yaml.Marshal(lf)
	if err != nil {
		return fmt.Errorf("marshaling lock file: %w", err)
	}

	header := []byte("# agentskills.lock — DO NOT EDIT MANUALLY\n# Generated by: agentskills vendor\n\n")
	content := append(header, data...)

	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("writing lock file: %w", err)
	}
	return nil
}

// Remove deletes a skill entry from the lock file.
func (lf *LockFile) Remove(name string) {
	delete(lf.Skills, name)
}

// Set adds or updates a skill entry in the lock file.
func (lf *LockFile) Set(name string, skill LockedSkill) {
	if lf.Skills == nil {
		lf.Skills = make(map[string]LockedSkill)
	}
	lf.Skills[name] = skill
}

// Get returns a locked skill entry and whether it exists.
func (lf *LockFile) Get(name string) (LockedSkill, bool) {
	if lf.Skills == nil {
		return LockedSkill{}, false
	}
	s, ok := lf.Skills[name]
	return s, ok
}
